# This is the RoboClerk AzureDevOps plugin configuration

AccessToken = "olyjeywxzkkw5vhtpa7nym3f7wnud4fa3ja25vyt2jis3wtliipa"
OrganizationName = "meindert"
ProjectName = "RoboClerk"

# The following allows you to indicate the work item names that map
# to various entities in the RoboClerk software
SystemRequirement = "Epic"
SoftwareRequirement = "User Story"
DocumentationRequirement = "Documentation"
DocContent = "DocContent"
SoftwareSystemTest = "Test Case"
Risk = "Risk"
Anomaly = "Bug"
SOUP = "SOUP"

# certain items in azure devops should be ignored because they are no longer
# relevant. Indicate which item statuses should be ignored.

Ignore = [ "Removed" ]