# This is the RoboClerk AzureDevOps plugin configuration

accessToken = ""
organizationName = "meindert"
projectName = "RoboClerk"

# if you want RoboClerk to ignore new Epics (for instance, in your backlog)
# set this to true
IgnoreNewProductRequirements = true