# This is the RoboClerk Redmine plugin configuration

RedmineAPIEndpoint = ""
RedmineAPIKey = ""

# The name of the project that we will be pulling from Redmine

RedmineProject = "Arcturus"

# The following allows you to indicate the redmine trackers that map
# to various entities in the RoboClerk software

SystemRequirement = "Specification"
SoftwareRequirement = "Feature"
SoftwareSystemTest = "Validation"
SoftwareUnitTest = "NA"
Risk = "NA"
Anomaly = "Bug"

# certain items in redmine should be ignored because they are no longer
# relevant. Indicate which item statuses should be ignored.

Ignore = [ "Rejected" ]

# In order to provide hyperlinks in the documents provide the redmine
# base URL here. NOTE: Ensure the URL ends with a single /
# If you do not wish the software to include hyperlinks, just set this
# variable to an empty string "".

RedmineBaseURL = ""