# This is the RoboClerk Redmine plugin configuration

RedmineAPIEndpoint = "http://localhost:3001/"
RedmineAPIKey = "014a75c443c18891c3baf8f7f2d2ce37aa27b94c"

# The name of the project that we will be pulling from Redmine

RedmineProject = "TestProject"

# The following allows you to indicate the redmine trackers that map
# to various entities in the RoboClerk software

SystemRequirement = "SystemRequirement"
SoftwareRequirement = "SoftwareRequirement"
DocumentationRequirement = "Documentation"
DocContent = "DocContent"
SoftwareSystemTest = "SoftwareSystemTest"
Risk = "Risk"
Anomaly = "Bug"
SOUP = "SOUP"

# certain items in redmine should be ignored because they are no longer
# relevant. Indicate which item statuses should be ignored.

Ignore = [ "Rejected" ]

# In order to provide hyperlinks in the documents provide the redmine
# base URL here. NOTE: Ensure the URL ends with a single /
# If you do not wish the software to include hyperlinks, just set this
# variable to an empty string "".

RedmineBaseURL = "http://localhost:3001/issues/"

# To support the use case of documenting different versions of the software
# for example an RUO vs IVD version with different features or a US vs an EU
# version of the software, the RoboClerk Redmine Plugin supports providing 
# fields here that will cause it to ignore system requirements and all  
# attached items as well. As an example, by providing the value 
# ReleaseType = ["IVD"]
# Roboclerk will look for a field named "ReleaseType" in the system requirements 
# and if the field value is in the list (e.g. "IVD") will ignore that system
# requirement and all attached items.

[IgnoreRequirements]
	ReleaseType = [ "IVD" ]