# This is the RoboClerk Redmine plugin configuration

RedmineAPIEndpoint = "http://192.168.4.40:3001/"
RedmineAPIKey = "014a75c443c18891c3baf8f7f2d2ce37aa27b94c"

# The name of the project that we will be pulling from Redmine

RedmineProject = "TestProject"

# The following allows you to indicate the redmine trackers that map
# to various entities in the RoboClerk software

SystemRequirement = "Specification"
SoftwareRequirement = "Feature"
DocumentationRequirement = "Documentation"
DocContent = "DocContent"
SoftwareSystemTest = "Validation"
UnitTest = "NA"
Risk = "Risk"
Anomaly = "Bug"
SOUP = "SOUP"

# certain items in redmine should be ignored because they are no longer
# relevant. Indicate which item statuses should be ignored.

Ignore = [ "Rejected" ]

# In order to provide hyperlinks in the documents provide the redmine
# base URL here. NOTE: Ensure the URL ends with a single /
# If you do not wish the software to include hyperlinks, just set this
# variable to an empty string "".

RedmineBaseURL = "http://localhost:3001/issues/"