# This is the RoboClerk Gradle Dependency plugin configuration

# what configuration of Gradle to use the dependencies from
GradleConfiguration = "runtimeClassPath"

# the commandline to call to run Gradle. The project root directory can be added using to following value:
# %PROJECTROOT% = the directory containing the project root

CommandlineToGradle = "docker run --rm -v \"%PROJECTROOT%\":/home/gradle/project -w /home/gradle/project gradle gradle"

