# This is the RoboClerk configuration file

# Provide the names of the DataSource plugin(s) in a comma seperated list
# For example: DataSourcePlugin = [ "AzureDevOpsSLMSPlugin", "RedmineCSVSLMSPlugin" ]
DataSourcePlugin = [ "RedmineCSVSLMSPlugin" ]

# RoboClerk will search for plugins in the subdirectories of the plugin dirs.
# For example: PluginDirs = [ "c:/temp/plugins" ]
PluginDirs = [ "I:/code/RoboClerk/RoboClerk.RedmineCSV/bin/Debug/net6.0" ]

# The output directory is where the output files and logs are placed
OutputDirectory = "C:/temp/roboclerk"

# Logging level (DEBUG or INFO)
LogLevel = "INFO"


