# This is the RoboClerk configuration file

# Provide the name of the file provider plugin. The default is the LocalFileProviderPlugin 
# that assumes files are being read off of the local filesystem. The other is the
# SharePointFileProviderPlugin if the files are hosted in a sharepoint library.
FileProviderPlugin = "SharePointFileProviderPlugin"

# Provide the names of the DataSource plugin(s) in a comma seperated list
# For example: DataSourcePlugin = [ "AzureDevOpsSLMSPlugin", "RedmineCSVSLMSPlugin" ]
DataSourcePlugin = [ "RedmineSLMSPlugin", "DependenciesFilePlugin", "UnitTestFNPlugin", "AnnotatedUnitTestPlugin", "TestResultsFilePlugin" ]

# Indicate what AI system plugin you'd like to use (if any). Provide "" for no AI plugin.
# If you have an OpenAI key, you can use "OpenAIPlugin"
AISystemPlugin = ""

# RoboClerk will search for plugins in the subdirectories of the plugin dir.
# For example: PluginDir = "c:/temp/plugins". Note that the plugins are included
# with the RoboClerk container, so when using the container, this should point to
# /home/RoboClerk/plugins
PluginDir = "{PLUGINROOT}/plugins"

# The configuration files for the plugins may be in a different location than the 
# plugins themselves. E.g. when executing RoboClerk in a docker environment. If
# the following configuration item is empty, then the standard location 
# in the Configuration subdir of the plugins directory is assumed.
PluginConfigurationDir = "{DOCUMENTATIONROOT}RoboClerk_input/PluginConfig"

# The output directory is where the output files and logs are placed
OutputDirectory = "{DOCUMENTATIONROOT}RoboClerk_output"

# Clear output directory before creating new output files.
ClearOutputDir = "True"

# Logging level (DEBUG, INFO or WARN)
LogLevel = "WARN"

# Output format (ASCIIDOC or HTML)
OutputFormat = "{OUTPUTFORMAT}"


