# SharePoint File Provider Configuration
# This file configures the SharePoint file provider plugin for RoboClerk

# The SharePoint site URL (required)
# Example: "contoso.sharepoint.com" or "contoso.sharepoint.com/sites/mysite"
SiteUrl = ""

# Azure AD OAuth2 Client ID (required)
# This is the Application (client) ID from your Azure AD app registration
ClientId = ""

# Azure AD OAuth2 Client Secret (required)
# This is the client secret from your Azure AD app registration
ClientSecret = ""

# Azure AD Tenant ID (required)
# This is your Azure AD tenant ID (directory ID)
TenantId = ""

# Drive ID (required)
# The ID of the SharePoint document library to use
# You can find the Drive ID by calling the Microsoft Graph API: /sites/{site-id}/drives
DriveId = ""