# This is the RoboClerk Redmine CSV plugin configuration

ImportFilename = "I:/temp/Roboclerk_input/Arcturus_final.csv"

# The following allows you to indicate the redmine tracker that maps
# to various entities in the RoboClerk software

ProductLevelRequirement = "Specification"
SoftwareLevelRequirement = "Feature"
TestCase = "Validation"
Bug = "Bug"

# certain items in redmine should be ignored because they are no longer
# relevant. Indicate which item statuses should be ignored.

Ignore = [ "Rejected" ]

# In order to provide hyperlinks in the documents provide the redmine
# base URL here. NOTE: Ensure the URL ends with a single /
# If you do not wish the software to include hyperlinks, just set this
# variable to an empty string "".

RedmineBaseURL = ""
